### ISSUE TITLE
[2.0] 使用说明

### ISSUE THREAD

**Issue by lilijialiang** [legoflow/legoflow#12]
### 🎉 vs 1.x

* 优化了一些 UI 界面操作
* 删减了一些极少使用的功能
    * ~~https / other / output / dist / packCommon / WebP / Proxy / isPackVueStyle / isUglifyJs~~
    * ~~legolib / Tiny / 上传预览 / 组件模块开发 / ...~~
* 增加了一些较先进的功能
    * babel 7 ( optional-chaining / ... ) / WebPack 4.5 / ...

### 🎉 全局设置

* 实验室：该配置打开后会接受 Preview 版本的提示，以及一些实验性功能
* NodeBin：Shell 模块的扩展 ( [详情](https://github.com/legoflow/legoflow/wiki/9.5.-%E5%A6%82%E4%BD%95%E7%90%86%E8%A7%A3-node-bin) )

### 🎉 配置

增加支持 legoflow.json / legolfow.yml / legoflow.js 扩展配置文件的阅读性、扩展性

默认使用 **legoflow.yml**，e.g.

```yml
# 项目名称
name: xxx

# 创建项目使用的 LegoFlow 版本号
version: 2.0.0-beta.1

# 项目类型
type: vue

# 是否使用 REM 适配。启动该选项后，_img.scss 会以 REM 为单位
REM: true

# 是否对 JS 进行 ES.Next 语法的编译
ES.Next: true

# 注入 webpack 别名 --- https://webpack.js.org/loaders/css-loader/#alias ---
alias: 
    axios: ./node_modules/axios
    jquery: ./src/assets/jquery.min.js

# 注入 webpack 全局对象 --- https://webpack.js.org/guides/shimming/#shimming-globals --- 
global: 
    $: jquery
    jquery: jquery
    jQuery: jquery

# 注入 webpack externals --- https://webpack.js.org/configuration/externals/#externals ---
externals:
    vue: Vue

# 各种环境配置
env:
    dev-test:
        alias:
            axios: ./src/assets/axios.min.js
    preview:
        workflow.build:
            html.resourcesDomain: https://preview.com
    test:
        workflow.build:
            html.resourcesDomain: https://test.com
    production:
        workflow.build:
            html.resourcesDomain: https://production.com

# 开发工作流相关配置
workflow.dev:
    # 监听额外的文件夹，进行热刷新
    watch.reload:
        - ./src/test/**/*

    # 用户配置参数
    # 根据用户输入 webpack define 插件变量 --- https://webpack.js.org/plugins/define-plugin/#usage ---
    # * 全部用户在 JS 文件中变量 process.args.token4Common 编译为 abc
    # 用户为 test1，在 JS 文件中变量 process.args.token4User 编译为 123
    # 用户为 test2，在 JS 文件中变量 process.args.token4User 编译为 321
    user.args:
        *:
            token4Common: abc
        test1:
            token4User: 123
        test2:
            token4User: 321

    # 指向环境
    env: dev-test

# 构建工作流相关配置
workflow.build:
    # 类型于 1.x 版本 assets，构建时候对 html 文件引入的资源加入主域
    # 例如：<script src="./js/main.js"></script>
    # 输出：<script src="https://legox.org/js/main.js"></script>
    html.resourcesDomain: https://legox.org

    # 对资源生成 时间戳 ( timestamp ) / 版本号 ( version ) / 无 ( '' )
    # 时间戳：<script src="./js/main.js?t=1523518772795"></script>
    # 版本号：<script src="./js/main.js?v=0.0.1"></script>
    # 无：<script src="./js/main.js"></script>
    cache: version

    # 用户配置参数
    user.args:
        *:
            token4Common: abc
        test1:
            token4User: 123
        test2:
            token4User: 321

    # 指向环境
    env: preview

    # 需要执行的 shell 模块文件
    shell: ./shell.js

    # 是否仅仅执行 Shell 模块
    onlyRunShell: true
```
